a, b = int(input('Enter first number ')), int(input('Enter second number '))
print('sum of given number  ', (a+b))
print('difference of given number  ', (a-b))
print('multiples of given number  ', (a*b))
print('division of given numbers  ', (a/b))
